name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  # Pre-deployment validation
  pre-deploy:
    name: Pre-deployment
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

  # Post-deployment validation
  post-deploy:
    name: Post-deployment
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: Wait for Vercel deployment
        run: sleep 60

      - name: Health check staging
        if: github.event.workflow_run.head_branch == 'develop'
        run: |
          echo "Staging deployment completed for branch: develop"
          echo "Vercel will handle the actual deployment"

      - name: Health check production
        if: github.event.workflow_run.head_branch == 'main'
        run: |
          echo "Production deployment completed for branch: main"
          echo "Vercel will handle the actual deployment"

      - name: Deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.event.workflow_run.head_branch }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.event.workflow_run.head_sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ github.event.workflow_run.head_branch == 'main' && 'Production' || 'Staging' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ✅ Pre-deployment validation completed" >> $GITHUB_STEP_SUMMARY
          echo "**Deployment:** Handled by Vercel" >> $GITHUB_STEP_SUMMARY 